site_name: Tennessee Mesh Network
site_url: https://tnmesh.org
site_description: A project dedicated to providing information for the Meshtastic network in the state of Tennessee.

repo_url: https://github.com/tnmesh/homepage

# Navigation
nav:
  - Home: index.md
  - Connect to MQTT: mqtt.md
  - Guides:
    - guides/settings.md
  - Events:
    - events/index.md
  - Resources:
    - High SNR Connections: resources/connections.md
    - Infrastructure Nodes: resources/infrastructure-nodes.md

# Theming
theme:
  name: material

  palette:
    scheme: slate

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

# Plugins
plugins:
  - search
  - macros
  - blog:
      authors_file: "{blog}/.authors.yml"
      blog_dir: events

# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# CSS
extra_css:
  - static/styles/extra.css

extra_javascript:
  - static/js/malla.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/7bFRR8Jt22
      name: Join our Discord
